// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3LSEMcMJSSchgDJrCtTwAdmNeeVdEKE',
    appId: '1:978954360834:web:82352c1e39b865bb252f1b',
    messagingSenderId: '978954360834',
    projectId: 'fnb-platform-2dfd9',
    authDomain: 'fnb-platform-2dfd9.firebaseapp.com',
    storageBucket: 'fnb-platform-2dfd9.firebasestorage.app',
    measurementId: 'G-R8CVES260Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQkArqcu2Wno83e0YryQkNiX0RntkD8A',
    appId: '1:978954360834:android:d01c9abf6701abfb252f1b',
    messagingSenderId: '978954360834',
    projectId: 'fnb-platform-2dfd9',
    storageBucket: 'fnb-platform-2dfd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYeQJ0l0BYKYjvkMjJJrYWa18c5h1lWLs',
    appId: '1:978954360834:ios:242f3b7798ebb9a3252f1b',
    messagingSenderId: '978954360834',
    projectId: 'fnb-platform-2dfd9',
    storageBucket: 'fnb-platform-2dfd9.firebasestorage.app',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYeQJ0l0BYKYjvkMjJJrYWa18c5h1lWLs',
    appId: '1:978954360834:ios:242f3b7798ebb9a3252f1b',
    messagingSenderId: '978954360834',
    projectId: 'fnb-platform-2dfd9',
    storageBucket: 'fnb-platform-2dfd9.firebasestorage.app',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3LSEMcMJSSchgDJrCtTwAdmNeeVdEKE',
    appId: '1:978954360834:web:27de4b05ced61fce252f1b',
    messagingSenderId: '978954360834',
    projectId: 'fnb-platform-2dfd9',
    authDomain: 'fnb-platform-2dfd9.firebaseapp.com',
    storageBucket: 'fnb-platform-2dfd9.firebasestorage.app',
    measurementId: 'G-90356RG2GK',
  );
}
